apiVersion: v1
kind: ConfigMap
metadata:
  name: weatherapp-config
  namespace: default
data:
  config.yaml: |
    source_city_map:
      open_weather:
        - Tel Aviv
        - Paris
      csv_file:
        - Rehovot
      weather_api:
        - Sydney
        - Tel Aviv
        - Berlin
    polling_time: 5
  data.csv: |
    city,temperature,description
    Rehovot,18.5,"Scattered clouds"
    Sydney,22.1,"Sunny"