apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp-container
        image: theclaw44/weather_app:latest
        volumeMounts:
          - name: config-volume
            mountPath: /app/config/config.yaml
            subPath: config.yaml
          - name: config-volume
            mountPath: /app/data/data.csv
            subPath: data.csv
        envFrom:
          - secretRef:
              name: weatherapp-secret
      volumes:
        - name: config-volume
          configMap:
            name: weatherapp-config