apiVersion: v1
kind: Secret
metadata:
  name: weatherapp-secret
type: Opaque
stringData:
  LOCAL_CSV_PATH: "/app/example_data/data.csv"
  WEATHERAPI_API_KEY: "[KEY]"
  OPENWEATHER_API_KEY: "[KEY]"
  WEATHERAPI_CURRENT_WEATHER_ENDPOINT: "api.weatherapi.com/v1/current.json"
  OPENWEATHER_CURRENT_WEATHER_ENDPOINT: "api.openweathermap.org/data/2.5/weather"
  LOGZ_API_ENDPOINT: "listener-eu.logz.io"
  LOGZ_API_TOKEN: "[TOKEN]"